/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DichVu;
import Model.NhanVien;
import Model.QLBH;
import controller.IOFile;
import controller.TrongException;
import controller.DTException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quach
 */
public class main extends javax.swing.JFrame {

    DefaultTableModel tmDV, tmNV, tmQL;
    String fDV, fNV, fQL;
    List<DichVu> listDV;
    List<QLBH> listQL;
    List<NhanVien> listNV;

    public main() {
        initComponents();
        fDV = "src/controller/dv.dat";
        fNV = "src/controller/nv.dat";
        fQL = "src/controller/ql.dat";
        String[] dv = {"ma dv", "ten dv ", "nhom DV", "chi phi", "gia cuoc"};
        String[] nv = {"ma nv", "ten nv ", "dia chi", "sdt"};
        String[] ql = {"ma nv", "ten nv ", "ma dv", "ten dv", "so luong"};
        tmDV = new DefaultTableModel(dv, 0);
        tmNV = new DefaultTableModel(nv, 0);
        tmQL = new DefaultTableModel(ql, 0);
        jTable1.setModel(tmDV);
        jTable2.setModel(tmNV);
        jTable3.setModel(tmQL);

        loadDV();
        loadNV();
        loadQL();
        showDV(listDV);
        showNV(listNV);
        showQL(listQL);
        loadCBDV();
        loadCBNV();

    }

    public void loadDV() {
        File f = new File(fDV);
        if (f.exists()) {
            listDV = IOFile.doc(fDV);
        } else {
            listDV = new ArrayList<>();

        }
    }

    public void loadNV() {
        File f = new File(fNV);
        if (f.exists()) {
            listNV = IOFile.doc(fNV);
        } else {
            listNV = new ArrayList<>();
        }
    }

    private NhanVien getNVByMa(int ma) {
        for (int i = 0; i < tmNV.getRowCount(); i++) {
            if (Integer.parseInt(tmNV.getValueAt(i, 0).toString()) == ma) {
                return new NhanVien(ma,
                        tmNV.getValueAt(i, 1).toString(),
                        tmNV.getValueAt(i, 2).toString(),
                        tmNV.getValueAt(i, 3).toString());
            }
        }
        return null;
    }

    private DichVu getDVByMa(int ma) {
        for (int i = 0; i < tmDV.getRowCount(); i++) {
            if (Integer.parseInt(tmDV.getValueAt(i, 0).toString()) == ma) {
                return new DichVu(ma,
                        tmDV.getValueAt(i, 1).toString(),
                        tmDV.getValueAt(i, 2).toString(),
                        Double.parseDouble(tmDV.getValueAt(i, 3).toString()),
                        Double.parseDouble(tmDV.getValueAt(i, 4).toString()));
            }
        }
        return null;
    }

    public void loadQL() {
        File f = new File(fQL);
        if (f.exists()) {
            listQL = IOFile.doc(fQL);
        } else {
            listQL = new ArrayList<>();
        }
    }

    public void showDV(List<DichVu> list) {
        tmDV.setRowCount(0);
        for (DichVu i : list) {
            tmDV.addRow(i.toObject());
        }
    }

    public void showQL(List<QLBH> list) {
        tmQL.setRowCount(0);
        for (QLBH i : list) {
            int maNV = i.getMaNV();
            String tenNV = getNVByMa(maNV).getTen();
            int maDV = i.getMaDV();
            String tenDV = getDVByMa(maDV).getTen();
            int sl = i.getSoLuong();
            tmQL.addRow(new Object[]{maNV, tenNV, maDV, tenDV, sl});
        }
    }

    public void showNV(List<NhanVien> list) {
        tmNV.setRowCount(0);
        for (NhanVien i : list) {
            tmNV.addRow(i.toObject());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThemDV = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnThemNV = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        p3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnThemDV1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnLuu2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        btnTim1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnThemDV.setText("Them DV");
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setText("Luu vao File");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel1.setText("Ma DV");

        jLabel2.setText("Ten DV");

        jLabel3.setText("Nhom");

        jLabel4.setText("Chi phi");

        jLabel5.setText("Cuoc");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dich vu thue bao tra truoc", "Dich vu thue bao tra truoc", "Dich vu gia tri gia tang" }));

        btnTim.setText("Tim kiem");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(btnThemDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addGap(124, 124, 124)
                        .addComponent(btnLuu)))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTim)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jComboBox1, 0, 157, Short.MAX_VALUE)))
                    .addComponent(jTextField9))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDV)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnTim))
                .addGap(0, 167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin dich vu", p1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnThemNV.setText("Them NV");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu1.setText("Luu vao File");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ma NV");

        jLabel7.setText("Ten NV");

        jLabel9.setText("Dia chi");

        jLabel10.setText("So DT");

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(btnThemNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(124, 124, 124)
                        .addComponent(btnLuu1)))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnSua)
                    .addComponent(btnLuu1))
                .addGap(0, 167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin nhan vien", p2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnThemDV1.setText("Them");
        btnThemDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDV1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xoa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnLuu2.setText("Luu vao File");
        btnLuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Ma NV");

        jLabel11.setText("Ma DV");

        jLabel13.setText("So luong");

        btnTim1.setText("Tim kiem");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(btnThemDV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa1)
                        .addGap(124, 124, 124)
                        .addComponent(btnLuu2)))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTim1)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(23, 23, 23)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextField14))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDV1)
                    .addComponent(btnXoa1)
                    .addComponent(btnLuu2)
                    .addComponent(btnTim1))
                .addGap(0, 167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QLBH", p3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        int n = listNV.size();
        if (n > 0) {
            NhanVien.setSma(listNV.get(n - 1).getMaNV() + 1);
            jTextField3.setText(NhanVien.getSma() + "");
            String ten, dchi;
            String sdt;
            try {
                ten = jTextField6.getText();
                dchi = jTextField7.getText();
                sdt = jTextField8.getText();
                NhanVien nv = new NhanVien(ten, dchi, sdt);
                tmNV.addRow(nv.toObject());
                listNV.add(nv);
            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
                return;
            } catch (DTException e) {
                JOptionPane.showMessageDialog(this, "nhap vao so");
                return;
            }
        } else {

            jTextField3.setText(NhanVien.getSma() + "");
            String ten, dchi;
            String sdt;
            try {
                ten = jTextField6.getText();
                dchi = jTextField7.getText();
                sdt = jTextField8.getText();
                NhanVien nv = new NhanVien(ten, dchi, sdt);
                tmNV.addRow(nv.toObject());
                listNV.add(nv);
            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
                return;
            } catch (DTException e) {
                JOptionPane.showMessageDialog(this, "nhap vao so");
                return;
            }
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
//        try {
//            // TODO add your handling code here:
//            DichVu dv =new DichVu("Vien thong", "Goi", 76.0, 85.0);
//            listDV.add(dv);
//        } catch (TrongException ex) {
//            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        

        int n = listDV.size();
        if (n > 0) {
            DichVu.setSma(listDV.get(n - 1).getMa() + 1);
            jTextField1.setText(DichVu.getSma() + "");
            String ten, nhom;
            double cp, cuoc;
            try {
                ten = jTextField2.getText();
                nhom = jComboBox1.getSelectedItem().toString();
                cp = Double.parseDouble(jTextField4.getText());
                cuoc = Double.parseDouble(jTextField5.getText());
                DichVu dv = new DichVu(ten, nhom, cp, cuoc);
                tmDV.addRow(dv.toObject());
                listDV.add(dv);

            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
                return;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "nhap vao so");
                return;
            }
        } else {
            String ten, nhom;
            double cp, cuoc;
            try {
                ten = jTextField2.getText();
                nhom = jComboBox1.getSelectedItem().toString();
                cp = Double.parseDouble(jTextField4.getText());
                cuoc = Double.parseDouble(jTextField5.getText());
                DichVu dv = new DichVu(ten, nhom, cp, cuoc);
                tmDV.addRow(dv.toObject());
                listDV.add(dv);

            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
                return;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "nhap vao so");
                return;
            }
        }
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r >= 0 && r < jTable1.getRowCount()) {
            tmDV.removeRow(r);
            listDV.remove(r);
        } else {
            JOptionPane.showMessageDialog(this, "chon dong xoa");
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fDV, (ArrayList<DichVu>) listDV);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fNV, (ArrayList<NhanVien>) listNV);
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        String ten, dc, sdt;
        int ma;
        if (r >= 0 && r < jTable2.getRowCount()) {
            ten = jTextField6.getText();
            dc = jTextField7.getText();
            sdt = jTextField8.getText();
            tmNV.setValueAt(ten, r, 1);
            tmNV.setValueAt(dc, r, 2);
            tmNV.setValueAt(sdt, r, 3);
            ma = Integer.parseInt(jTextField3.getText());
            NhanVien nv = new NhanVien(ma, sdt, ten, dc);
            listNV.set(r, nv);
        } else {
            JOptionPane.showMessageDialog(this, "chon dong xoa");
            return;
        }

    }//GEN-LAST:event_btnSuaActionPerformed
    private void loadCBNV() {
        jComboBox2.removeAllItems();
        for (int i = 0; i < tmNV.getRowCount(); i++) {
            jComboBox2.addItem(tmNV.getValueAt(i, 0).toString());
        }
    }

    private void loadCBDV() {
        jComboBox3.removeAllItems();
        for (int i = 0; i < tmDV.getRowCount(); i++) {
            jComboBox3.addItem(tmDV.getValueAt(i, 0).toString());
        }
    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        jTextField3.setText(tmNV.getValueAt(r, 0).toString());
        jTextField6.setText(tmNV.getValueAt(r, 1).toString());
        jTextField7.setText(tmNV.getValueAt(r, 2).toString());
        jTextField8.setText(tmNV.getValueAt(r, 3).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String key = jTextField9.getText().trim().toLowerCase();
        List<DichVu> l = new ArrayList<>();
        for (DichVu i : listDV) {
            if (i.getTen().trim().toLowerCase().contains(key) || i.getNhomDV().trim().toLowerCase().contains(key)) {
                l.add(i);
            }
        }
        showDV(l);
    }//GEN-LAST:event_btnTimActionPerformed

    private boolean tontai(int maNV, int maDV) {
        for (int i = 0; i < tmQL.getRowCount(); i++) {
            if (Integer.parseInt(tmQL.getValueAt(i, 0).toString()) == maNV
                    && Integer.parseInt(tmQL.getValueAt(i, 2).toString()) == maDV) {
                return true;
            }
        }
        return false;
    }

    private void btnThemDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDV1ActionPerformed

        int maNV, maDV;
        String sl;
        try {
            maNV = Integer.parseInt(jComboBox2.getSelectedItem().toString());
            maDV = Integer.parseInt(jComboBox3.getSelectedItem().toString());
            sl = jTextField12.getText();
            if (!tontai(maNV, maDV)) {
                QLBH ql = new QLBH(maNV, maDV, sl);

                tmQL.addRow(ql.toObject());
                listQL.add(ql);
                showQL(listQL);
            } else {
                JOptionPane.showMessageDialog(this, "Da ton tai");
            }

        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            return;
        }

    }//GEN-LAST:event_btnThemDV1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        int r = jTable3.getSelectedRow();
        if(r>0||r<=jTable3.getRowCount()){
            tmQL.removeRow(r);
            listQL.remove(r);
        }
         else {
            JOptionPane.showMessageDialog(this, "chon dong xoa");
            return;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnLuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu2ActionPerformed
        IOFile.viet(fQL, (ArrayList<QLBH>) listQL);     // TODO add your handling code here:
    }//GEN-LAST:event_btnLuu2ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        String key = jTextField14.getText().trim().toLowerCase();
        List<QLBH> l = new ArrayList<>();
        for (QLBH i : listQL) {
            if (getNVByMa(i.getMaNV()).getTen().trim().toLowerCase().contains(key) || getDVByMa(i.getMaDV()).getTen().trim().toLowerCase().contains(key)) {
                l.add(i);
            }
        }
        showQL(l);       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnLuu2;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnThemDV1;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    // End of variables declaration//GEN-END:variables
}
